[package]
name = "randomrust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
actix-web = "4.3.1"
askama = "0.12.0"
log = "0.4.20"
pretty_env_logger = "0.5.0"

